$(document).ready(function () {

    let tree = [
        {class: "dot sqr green", id: 3},
        {class: "dot sqr green", id: 4},
        {class: "dot sqr green", id: 5},
        {class: "dot sqr green", id: 6},
        {class: "dot sqr green", id: 10},
        {class: "dot sqr green", id: 11},
        {class: "dot sqr green", id: 17},
        {class: "dot sqr green", id: 18},
        {class: "dot sqr green", id: 19},
        {class: "dot sqr green", id: 20},
        {class: "dot sqr green", id: 21},
        {class: "dot sqr green", id: 22},
        {class: "dot sqr green", id: 23},
        {class: "dot sqr green", id: 24},
        {class: "dot sqr green", id: 25},
        {class: "dot sqr green", id: 26},
        {class: "dot sqr green", id: 27},
        {class: "dot sqr green", id: 28},
        {class: "dot sqr green", id: 32},
        {class: "dot sqr green", id: 33},
        {class: "dot sqr green", id: 34},
        {class: "dot sqr green", id: 35},
        {class: "dot sqr green", id: 36},
        {class: "dot sqr green", id: 37},
        {class: "dot sqr green", id: 38},
        {class: "dot sqr green", id: 39},
        {class: "dot sqr green", id: 40},
        {class: "dot sqr green", id: 41},
        {class: "dot sqr green", id: 42},
        {class: "dot sqr green", id: 43},
        {class: "dot sqr green", id: 44},
        {class: "dot sqr green", id: 48},
        {class: "dot sqr green", id: 49},
        {class: "dot sqr orange", id: 50},
        {class: "dot sqr orange", id: 51},
        {class: "dot sqr orange", id: 53},
        {class: "dot sqr orange", id: 56},
        {class: "dot sqr green", id: 58},
        {class: "dot sqr green", id: 59},
        {class: "dot sqr green", id: 60},
        {class: "dot sqr green", id: 64},
        {class: "dot sqr green", id: 65},
        {class: "dot sqr orange", id: 67},
        {class: "dot sqr orange", id: 68},
        {class: "dot sqr orange", id: 72},
        {class: "dot sqr orange", id: 73},
        {class: "dot sqr orange", id: 74},
        {class: "dot sqr green", id: 75},
        {class: "dot sqr orange", id: 84},
        {class: "dot sqr orange", id: 85},
        {class: "dot sqr orange", id: 87},
        {class: "dot sqr orange", id: 88},
        {class: "dot sqr orange", id: 101},
        {class: "dot sqr orange", id: 102},
        {class: "dot sqr orange", id: 103},
        {class: "dot sqr orange", id: 117},
        {class: "dot sqr orange", id: 118},
        {class: "dot sqr orange", id: 132},
        {class: "dot sqr orange", id: 133},
        {class: "dot sqr orange", id: 134},
        {class: "dot sqr orange", id: 148},
        {class: "dot sqr orange", id: 149},
        {class: "dot sqr orange", id: 150},
        {class: "dot sqr green", id: 157},
        {class: "dot sqr green", id: 158},
        {class: "dot sqr green", id: 159},
        {class: "dot sqr orange", id: 163},
        {class: "dot sqr orange", id: 164},
        {class: "dot sqr orange", id: 165},
        {class: "dot sqr orange", id: 166},
        {class: "dot sqr orange", id: 167},
        {class: "dot sqr green", id: 172},
        {class: "dot sqr green", id: 173},
        {class: "dot sqr green", id: 174},
        {class: "dot sqr green", id: 175},
        {class: "dot sqr green", id: 176},
        {class: "dot sqr green", id: 177},
        {class: "dot sqr green", id: 178},
        {class: "dot sqr green", id: 179},
        {class: "dot sqr green", id: 180},
        {class: "dot sqr green", id: 181},
        {class: "dot sqr green", id: 182},
        {class: "dot sqr green", id: 183},
        {class: "dot sqr green", id: 184},
        {class: "dot sqr green", id: 185},
        {class: "dot sqr green", id: 186},
        {class: "dot sqr green", id: 187},
        {class: "dot sqr green", id: 188},
        {class: "dot sqr green", id: 189},
        {class: "dot sqr green", id: 190},
        {class: "dot sqr green", id: 191},
        {class: "dot sqr green", id: 192},
        {class: "dot sqr green", id: 193},
        {class: "dot sqr green", id: 194},
        {class: "dot sqr green", id: 195},
        {class: "dot sqr green", id: 196},
        {class: "dot sqr green", id: 197},
        {class: "dot sqr green", id: 198},
        {class: "dot sqr green", id: 199},
        {class: "dot sqr green", id: 200},
        {class: "dot sqr green", id: 201},
        {class: "dot sqr green", id: 202},
        {class: "dot sqr green", id: 203},
        {class: "dot sqr green", id: 204},
        {class: "dot sqr green", id: 205},
        {class: "dot sqr green", id: 206},
        {class: "dot sqr green", id: 207}
    ];

    $('#tree').on('click', function (e) {
        for (let i = 0; i < 208; i++) {
            for (let j = 0; j < tree.length; j++) {
                if (tree[j].id === i) {
                    let currentDot = "#" + i;
                    $(currentDot).removeClass().addClass(tree[j].class);
                    console.log(currentDot);
                    console.log(tree[j].class);
                }
            }
        }
        
    });

});